# 函数（function）对给定的参数进行计算并返回值 np.sum(a)
# 方法（method）是和某个object绑定的 a.sum()
import numpy as np
a = np.arange(25).reshape(5, 5)
print(a)
# print(a.sum())
# print(a.max())
# print(a.sum(axis=-1))
# print(a.max(axis=-1))
# print(np.max(a, axis=-1))
# print(np.argmax(a, axis=-1))
# print(type(np.argmax(a, axis=-1)))
print(a.argmax(axis=0))
print(a.max())
print(a.mean(axis=0))
